{
 "title": "Servidores detalhado - Windows",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Host",
    "query": {}
   },
   {
    "name": "Grupo",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 1 },
   "options": {
    "content": "<div style=\"position: relative;\">\n  <img src=\"https://cdn.icon-icons.com/icons2/2699/PNG/512/grafana_logo_icon_171048.png\" alt=\"Descrição da Imagem\" style=\"max-width: 100%; height: auto; border-radius: 15px; box-shadow: 0 0 0px rgba(0, 0, 0, 0.3); display: inline-block;\">\n</div>\n"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 21, "x": 2, "y": 1 },
   "options": {
    "content": "<p style=\"  background-image: linear-gradient(to right top, #0b007e, #0e1b8e, #142f9d, #1d42ab, #2854b8, #146ac9, #007fd8, #0094e5, #00b0f2, #00cbf7, #00e4f6, #5ffbf1);\ncolor: white; border-radius: 50px 3px 50px 3px; padding: 5px; text-align: center; font-size: 17px; font-family: 'Roboto', sans-serif; transform: rotate(-45deg);\">\n    <strong>STATUS - WINDOWS</strong>\n</p>\n"
   },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "options": {
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Windows: Uptime" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Number of processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 5, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Windows: Number of processes" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Number of threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "Windows: Number of threads" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Visão geral",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 3 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": true,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTimeRange": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "ICMP loss",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "ICMP: ICMP loss" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Response time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "ICMP: ICMP response time" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 9 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "ICMP: ICMP loss" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 9 },
   "targets": [
    {
     "application": { "filter": "" },
     "evaltype": "0",
     "group": { "filter": "$Grupo" },
     "host": { "filter": "$Host" },
     "item": { "filter": "ICMP: ICMP response time" },
     "itemTag": { "filter": "" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 13, "x": 0, "y": 10 },
     "options": {
      "content": "<p style=\"  background-image: linear-gradient(to right top, #0b007e, #0e1b8e, #142f9d, #1d42ab, #2854b8, #146ac9, #007fd8, #0094e5, #00b0f2, #00cbf7, #00e4f6, #5ffbf1);\ncolor: white; border-radius: 50px 3px 50px 3px; padding: 5px; text-align: center; font-size: 17px; font-family: 'Roboto', sans-serif; transform: rotate(-45deg);\">\n    <strong>Memory / CPU %</strong>\n</p>\n"
     },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 11, "x": 13, "y": 10 },
     "options": {
      "content": "<p style=\"  background-image: linear-gradient(to right top, #0b007e, #0e1b8e, #142f9d, #1d42ab, #2854b8, #146ac9, #007fd8, #0094e5, #00b0f2, #00cbf7, #00e4f6, #5ffbf1);\ncolor: white; border-radius: 50px 3px 50px 3px; padding: 5px; text-align: center; font-size: 17px; font-family: 'Roboto', sans-serif; transform: rotate(-45deg);\">\n    <strong>CPU</strong>\n</p>\n"
     },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Available memory",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "application": { "filter": "Memory" },
       "evaltype": "0",
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "Windows: Available memory" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 9, "x": 4, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:823",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Available memory" ],
         "text": "setAlias(Memória disponível)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "Windows: Available memory" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:844",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "CPU" ],
         "text": "setAlias(CPU)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "Windows: CPU utilization" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "CPU Info",
     "type": "stat",
     "gridPos": { "h": 19, "w": 4, "x": 13, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAliasByRegex",
          "params": [
           { "name": "aliasByRegex", "type": "string" }
          ]
         },
         "params": [ "CPU [^:]+" ],
         "text": "setAliasByRegex()"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/.*CPU*./" },
       "itemTag": { "filter": "component: cpu" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Processor usage",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:264",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ " Number of processes" ],
         "text": "setAlias(Uso de processador por agente)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "Windows: Processor usage" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "CPU",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "Windows: CPU utilization" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Processor load",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 7, "x": 17, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:363",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Processor load 1min" ],
         "text": "setAlias(Uso de processador 1min)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "Windows: Processor load (1 min average)"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "acknowledged": 2,
        "count": false,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 0,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default",
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "showProblems": "problems",
       "slaInterval": "none",
       "slaProperty": { "name": "SLA", "property": "sla" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      },
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:405",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Processor load 5min" ],
         "text": "setAlias(Uso de processador15min)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "Windows: Processor load (5 min average)"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "acknowledged": 2,
        "count": false,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 0,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default",
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "showProblems": "problems",
       "slaInterval": "none",
       "slaProperty": { "name": "SLA", "property": "sla" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      },
      {
       "application": { "filter": "CPU" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:384",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Processor load 15min" ],
         "text": "setAlias(Uso de processador 5min)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "Windows: Processor load (15 min average)"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "acknowledged": 2,
        "count": false,
        "disableDataAlignment": false,
        "hostProxy": false,
        "hostsInMaintenance": false,
        "limit": 1001,
        "minSeverity": 0,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "sortProblems": "default",
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "showProblems": "problems",
       "slaInterval": "none",
       "slaProperty": "sla",
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 13, "x": 0, "y": 22 },
     "options": {
      "content": "<p style=\"  background-image: linear-gradient(to right top, #0b007e, #0e1b8e, #142f9d, #1d42ab, #2854b8, #146ac9, #007fd8, #0094e5, #00b0f2, #00cbf7, #00e4f6, #5ffbf1);\ncolor: white; border-radius: 50px 3px 50px 3px; padding: 5px; text-align: center; font-size: 17px; font-family: 'Roboto', sans-serif; transform: rotate(-45deg);\">\n    <strong>Memory RAM</strong>\n</p>\n"
     },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:765",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Total memory" ],
         "text": "setAlias(Memória Total)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "Windows: Total memory" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:744",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Used memory" ],
         "text": "setAlias(Memória disponível)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "Windows: Used memory" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 9, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:719",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Memory utilization" ],
         "text": "setAlias(Memória disponível)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "Windows: Used memory" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:740",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "Total memory" ],
         "text": "setAlias(Memória Total)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "Windows: Total memory" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 13, "x": 0, "y": 11 },
     "options": {
      "content": "<p style=\"  background-image: linear-gradient(to right top, #0b007e, #0e1b8e, #142f9d, #1d42ab, #2854b8, #146ac9, #007fd8, #0094e5, #00b0f2, #00cbf7, #00e4f6, #5ffbf1);\ncolor: white; border-radius: 50px 3px 50px 3px; padding: 5px; text-align: center; font-size: 17px; font-family: 'Roboto', sans-serif; transform: rotate(-45deg);\">\n    <strong>Average disk read/write queue length</strong>\n</p>\n"
     },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 11, "x": 13, "y": 11 },
     "options": {
      "content": "<p style=\"  background-image: linear-gradient(to right top, #0b007e, #0e1b8e, #142f9d, #1d42ab, #2854b8, #146ac9, #007fd8, #0094e5, #00b0f2, #00cbf7, #00e4f6, #5ffbf1);\ncolor: white; border-radius: 50px 3px 50px 3px; padding: 5px; text-align: center; font-size: 17px; font-family: 'Roboto', sans-serif; transform: rotate(-45deg);\">\n    <strong>Disk</strong>\n</p>\n"
     },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "title": "Average disk write queue length",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1440",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$__zbx_item" ],
         "text": "setAlias($__zbx_item)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/.*Average disk write queue length*/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 14, "w": 7, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:256",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$__zbx_item" ],
         "text": "setAlias($__zbx_item)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/.*Average disk write queue length*/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:277",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$__zbx_item" ],
         "text": "setAlias($__zbx_item)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/.*Average disk read queue length*./"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Total disk space",
     "type": "stat",
     "gridPos": { "h": 5, "w": 5, "x": 13, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/.*Total space*/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Free disk space %",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "Filesystems" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:115",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$__zbx_item" ],
         "text": "setAlias($__zbx_item)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/.*Free disk space on.*%.*/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Used disk space",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 5, "x": 13, "y": 18 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:628",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$__zbx_item" ],
         "text": "setAlias($__zbx_item)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/.*Used space*./" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:628",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$__zbx_item" ],
         "text": "setAlias($__zbx_item)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/.*Total space*./" },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Free disk space",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 18 },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:628",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$__zbx_item" ],
         "text": "setAlias($__zbx_item)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/Free disk space on [A-Z]:[^%]*$/"
       },
       "itemTag": { "filter": "component: storage" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Average disk read queue length",
     "type": "stat",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "functions": [
        {
         "$$hashKey": "object:1467",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "$__zbx_item" ],
         "text": "setAlias($__zbx_item)"
        }
       ],
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": {
        "filter": "/.*Average disk read queue length*/"
       },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 22, "x": 1, "y": 12 },
     "options": {
      "content": "<p style=\"  background-image: linear-gradient(to right top, #0b007e, #0e1b8e, #142f9d, #1d42ab, #2854b8, #146ac9, #007fd8, #0094e5, #00b0f2, #00cbf7, #00e4f6, #5ffbf1);\ncolor: white; border-radius: 50px 3px 50px 3px; padding: 5px; text-align: center; font-size: 17px; font-family: 'Roboto', sans-serif; transform: rotate(-45deg);\">\n    <strong>Traffic network</strong>\n</p>\n"
     },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "" },
       "host": { "filter": "" },
       "item": { "filter": "" },
       "itemTag": { "filter": "" },
       "options": {
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
       }
      }
     ]
    },
    {
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/.*Bits sent*./" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      },
      {
       "application": { "filter": "" },
       "evaltype": "0",
       "group": { "filter": "$Grupo" },
       "host": { "filter": "$Host" },
       "item": { "filter": "/.*Bits rec*./" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  }
 ]
}